apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-kc1g
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-kc1g@sha256:5a361a4d2c13011c0deeb34c83a2c940fea5e745477b0d5a92af36302eabab8d
        name: my-nodejs
        resources: {}
status: {}
